
import { DayPlan } from './types';

export const COURSE_CURRICULUM: DayPlan[] = [
  {
    day: 1,
    title: "The Foundation: AC Circuits & Complex Power",
    category: "Fundamentals",
    lessons: [
      {
        id: "1.1",
        title: "Single Phase AC Concepts",
        description: "Phasors, RMS values, and impedance.",
        content: "Understanding alternating current is the backbone of power systems. We start with sinusoidal steady-state analysis...",
        keywords: ["RMS", "Phasors", "Impedance"]
      },
      {
        id: "1.2",
        title: "Complex Power (S, P, Q)",
        description: "Active, Reactive, and Apparent power.",
        content: "Power isn't just Volts x Amps in AC. We have Real Power (P), Reactive Power (Q), and Apparent Power (S).",
        keywords: ["Power Factor", "Reactive Power", "VARs"]
      }
    ]
  },
  {
    day: 2,
    title: "Synchronous Machines & Generation",
    category: "Generation",
    lessons: [
      {
        id: "2.1",
        title: "The Synchronous Generator",
        description: "Principles of 3-phase EMF generation.",
        content: "Most electricity globally is generated by synchronous machines. Learn about the rotor, stator, and synchronization...",
        keywords: ["Rotor", "Stator", "Synchronous Speed"]
      }
    ]
  },
  {
    day: 3,
    title: "Transformers & The Per-Unit System",
    category: "Fundamentals",
    lessons: [
      {
        id: "3.1",
        title: "Power Transformers",
        description: "Equivalent circuits and efficiency.",
        content: "Transformers allow high-voltage transmission. We analyze their losses and leakage reactance.",
        keywords: ["Turns Ratio", "Hysteresis", "Leakage"]
      },
      {
        id: "3.2",
        title: "The Per-Unit (pu) System",
        description: "Simplifying multi-voltage network analysis.",
        content: "Calculations in networks with many transformers become messy. The per-unit system normalizes everything.",
        keywords: ["Base Power", "Base Voltage", "Normalization"]
      }
    ]
  },
  {
    day: 4,
    title: "Transmission Line Parameters",
    category: "Analysis",
    lessons: [
      {
        id: "4.1",
        title: "Inductance & Capacitance",
        description: "Modeling overhead lines.",
        content: "Geometry of conductors affects transmission line characteristics. We use GMD and GMR to calculate L and C.",
        keywords: ["GMD", "GMR", "Proximity Effect"]
      }
    ]
  },
  {
    day: 5,
    title: "Steady-State Analysis of Lines",
    category: "Analysis",
    lessons: [
      {
        id: "5.1",
        title: "Line Models (Short, Medium, Long)",
        description: "Pi and T-equivalent circuits.",
        content: "Depending on length, we use different approximations. Long lines require differential equations.",
        keywords: ["ABCD Parameters", "Ferranti Effect", "Voltage Regulation"]
      }
    ]
  },
  {
    day: 6,
    title: "Power Flow (Load Flow) Studies",
    category: "Analysis",
    lessons: [
      {
        id: "6.1",
        title: "Problem Formulation",
        description: "The Power Flow Equation.",
        content: "Finding V and Angle at every bus. This is the most common computer-aided study in power engineering.",
        keywords: ["Bus Admittance Matrix", "Slack Bus", "PV Bus"]
      },
      {
        id: "6.2",
        title: "Newton-Raphson Method",
        description: "Iterative solutions for complex networks.",
        content: "Why do we use Newton-Raphson? Because power equations are non-linear...",
        keywords: ["Jacobian Matrix", "Iteration", "Convergence"]
      }
    ]
  },
  {
    day: 7,
    title: "Review & Mid-Course Assessment",
    category: "Fundamentals",
    lessons: [
      {
        id: "7.1",
        title: "Mid-Term Review",
        description: "Consolidating Week 1 topics.",
        content: "Let's revisit transformers, per-unit, and basic load flow before moving to faults.",
        keywords: ["Review", "Summary"]
      }
    ]
  },
  {
    day: 8,
    title: "Symmetrical Fault Analysis",
    category: "Analysis",
    lessons: [
      {
        id: "8.1",
        title: "Balanced 3-Phase Faults",
        description: "Calculating short circuit currents.",
        content: "Determining circuit breaker ratings requires knowing the worst-case fault currents.",
        keywords: ["Short Circuit", "Thevenin Equivalent", "MVA Fault"]
      }
    ]
  },
  {
    day: 9,
    title: "Symmetrical Components",
    category: "Analysis",
    lessons: [
      {
        id: "9.1",
        title: "Positive, Negative, & Zero Sequences",
        description: "Fortescue's Theorem.",
        content: "Unbalanced faults are solved by decomposing the system into three balanced components.",
        keywords: ["Sequence Networks", "Zero Sequence", "Phase Shift"]
      }
    ]
  },
  {
    day: 10,
    title: "Unsymmetrical Faults",
    category: "Analysis",
    lessons: [
      {
        id: "10.1",
        title: "LG, LL, and LLG Faults",
        description: "Connecting sequence networks.",
        content: "Line-to-ground faults are the most common. We learn how to interconnect sequence diagrams to solve them.",
        keywords: ["Grounding", "Single Line to Ground"]
      }
    ]
  },
  {
    day: 11,
    title: "Power System Protection",
    category: "Protection",
    lessons: [
      {
        id: "11.1",
        title: "Relays and Circuit Breakers",
        description: "Isolation and coordination.",
        content: "How do we detect a fault? Overcurrent, Differential, and Distance relays.",
        keywords: ["Relay Coordination", "Current Transformer", "Circuit Breaker"]
      }
    ]
  },
  {
    day: 12,
    title: "Power System Stability",
    category: "Control",
    lessons: [
      {
        id: "12.1",
        title: "Transient Stability",
        description: "The Swing Equation and Equal Area Criterion.",
        content: "Can the system stay in sync after a massive disturbance? We analyze the rotor dynamics.",
        keywords: ["Critical Clearing Time", "Swing Curve", "Synchronizing Power"]
      }
    ]
  },
  {
    day: 13,
    title: "Control: AGC, AVR & FACTS",
    category: "Control",
    lessons: [
      {
        id: "13.1",
        title: "Frequency & Voltage Control",
        description: "Secondary control and reactive support.",
        content: "Automatic Generation Control (AGC) keeps frequency at 60Hz (or 50Hz). AVR controls voltage at the terminals.",
        keywords: ["Frequency Drop", "Voltage Collapse", "FACTS"]
      }
    ]
  },
  {
    day: 14,
    title: "The Modern Grid & Renewables",
    category: "Modern Grid",
    lessons: [
      {
        id: "14.1",
        title: "Renewable Integration",
        description: "Inverter-based resources (IBRs).",
        content: "Solar and Wind don't have mechanical inertia. How do we handle their variability?",
        keywords: ["Microgrids", "Smart Grid", "VPP"]
      }
    ]
  }
];
